dist: xenial
language: python
cache: pip
before_script:
- pip install --upgrade tox setuptools virtualenv

script: tox
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-coverage
    - python: 3.7
      env: TOXENV=py37-coverage
    - python: 3.7
      env: TOXENV=bandit
    - python: 3.7
      env: TOXENV=pylint
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=docs